### ISSUE TITLE
HCSEC-2024-05 - Vault Cert Auth Method Did Not Correctly Validate Non-CA Certificates

### ISSUE THREAD

**Issue by loafoe** [philips-software/cf-vault#56]
```[tasklist]
### Tasks
- [x] Update vault to 1.14.10 or newer
```

**Comment by nishwalshetty** [comment]
adding the link to reported vulnerability -https://discuss.hashicorp.com/t/hcsec-2024-05-vault-cert-auth-method-did-not-correctly-validate-non-ca-certificates/63382
